name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc -b

      - name: Build Web
        run: npm run build:web

      - name: Build Extension
        run: npm run build:extension

      - name: Pack Extension
        run: npm run pack:extension

      - name: Upload Extension ZIP
        uses: actions/upload-artifact@v4
        with:
          name: wikinote-extension
          path: frontend/dist/wikinote-extension.zip
          if-no-files-found: error

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: frontend/dist/wikinote-extension.zip
          body_path: frontend/CHANGELOG.md
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}

  autobump:
    # Auto-bump patch version on push to main (no tag required)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Auto bump patch, sync manifest, update CHANGELOG, tag
        run: node scripts/auto-bump.js

      - name: Push commit and tags
        run: |
          git push origin HEAD:main
          git push --tags
